services:
  laravel:
    container_name: laravel
    restart: unless-stopped
    build:
      context: ./
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - karya-budaya
    depends_on:
      - mysql
    ports:
      - 9000:9000

  mysql:
    image: mysql:latest
    container_name: mysql
    restart: unless-stopped
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - karya-budaya
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: karyabudaya2023
      MYSQL_USER: karya_budaya
      MYSQL_PASSWORD: karyabudaya2023
      MYSQL_DATABASE: karya_budaya_db

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    networks:
      - karya-budaya
    volumes:
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html
      - ./etc/ssl:/etc/ssl
      - ./var/log/nginx:/var/log/nginx

    depends_on:
      - laravel
      - mysql

    ports:
      - 80:80
      - 443:443

networks:
  karya-budaya:
    driver: bridge
